libblas:
  - 3.9 *openblas
libcblas:
  - 3.9 *openblas
liblapack:
  - 3.9 *openblas
liblapacke:
  - 3.9 *openblas
c_compiler_version:
  - 8
cxx_compiler_version:
  - 8
fortran_compiler_version:
  - 8
boost_cpp:
  - 1.74
mpi:
  - nompi
  - openmpi
build_type:
  - Debug
  - RelWithDebInfo
