libblas:
  - 3.8 *openblas
libcblas:
  - 3.8 *openblas
liblapack:
  - 3.8.0 *openblas
liblapacke:
  - 3.8.0 *openblas
c_compiler_version:
- '7'
cxx_compiler_version:
- '7'
fortran_compiler_version:
- '7'