{% set name = "dakota" %}
{% set version = "6.16.0" %}

package:
  name: {{ name }}
  version: {{ version }}

# source section handled in build.sh so that we can work around https://github.com/orgs/snl-dakota/discussions/12
# by downloading insecurely and checking the sha256 ourselves

build:
  number: 0
  skip: true  # [win or osx or py<38]

requirements:
  build:
    - curl
    - coreutils
    - tar
    - patch
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - openmpi
    # - pybind11
    - boost-cpp
    - libblas
    - libcblas
    - liblapack
    - python
    - perl
    - numpy
    - swig
    - doxygen
    - gsl
    - hdf5
        # - trilinos  # needs newer trilinos
  run:
    - boost-cpp
    - python
    - {{ pin_compatible("numpy") }}
        # - trilinos
test:
  files:
    - UQ.in
    - rosenbrock.py
  requires:
    - perl
  imports:
    - dakota
    - dakota.interfacing
    - dakota.interfacing.dprepro
  commands:
    - $PREFIX/share/dakota/test/dakota_test.perl --label-regex=AcceptanceTest
    - dakota -i UQ.in

about:
  home: https://dakota.sandia.gov
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: The Dakota project delivers software for optimization and uncertainty quantification.
  description: |
    The Dakota project delivers both state-of-the-art research and robust, 
    usable software for optimization and UQ. Broadly, the Dakota software's 
    advanced parametric analyses enable design exploration, model calibration, 
    risk analysis, and quantification of margins and uncertainty with computational
    models. The Dakota toolkit provides a flexible, extensible interface 
    between such simulation codes and its iterative systems analysis methods.
  doc_url: https://dakota.sandia.gov/content/610-reference-manual
  dev_url: https://dakota.sandia.gov/

extra:
  recipe-maintainers:
    - looooo
